repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
      args: [--line-length=120]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      args: [--config=.flake8]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.942
  hooks:
  - id: mypy
    args: ["--ignore-missing-imports",  "--namespace-packages", "--explicit-package-bases"]
    exclude: 'tests|scripts'
    additional_dependencies: ['types-requests']
